name: "Build and validate Go generated SDK"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.x.x'

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'

      - name: Install kiota
        run: dotnet tool install --global --prerelease Microsoft.OpenApi.Kiota

      - name: Run generation
        run: time kiota generate -l go --ll trace -o generated/go -n kiota -d schemas/updated/api.github.com.json --co

      - name: Build post-processing
        run: go build -o go-post-processor/post-processor go-post-processor/main.go

      - name: Run post-processing
        run: go-post-processor/post-processor $(pwd)/generated/go

      - name: Build generated and processed SDK
        run: |
          ls -R
          cd output
          go build ./...
